// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using ProyectoUniversidad.Models;

#nullable disable

namespace ProyectoUniversidad.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260531200000_agregarEntidadesAcademicas")]
    partial class agregarEntidadesAcademicas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
